### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by niutech** [burggraf/awesome-cosmo#2]
Next I have compiled Cosmopolitan Python 2.7.18 from [this repo](https://github.com/ahgamut/cpython/tree/cosmo_py27), could you please add it? [python.zip](https://github.com/burggraf/awesome-cosmo/files/6622322/python.zip)
There is a required file `lib/python27.zip`, which contains Python built-in libraries.

**Comment by burggraf** [comment]
Added.  Thank you!

**Comment by burggraf** [comment]
I'm getting an error trying to run anything:

My test file simply contains:

`print("This line will be printed.")`

The error I get:

```
./python.com test.py
Current dir is /root/py
Env-var PATH is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
sys.path in: lib/python27.zip:Lib:Lib/plat-linux2:build/lib.linux-x86_64-2.7
Traceback (most recent call last):
  File "lib/python27.zip/site.py", line 541, in <module>
  File "lib/python27.zip/site.py", line 523, in main
  File "lib/python27.zip/site.py", line 267, in addusersitepackages
  File "lib/python27.zip/site.py", line 242, in getusersitepackages
  File "lib/python27.zip/site.py", line 232, in getuserbase
  File "lib/python27.zip/sysconfig.py", line 525, in get_config_var
  File "lib/python27.zip/sysconfig.py", line 477, in get_config_vars
  File "lib/python27.zip/sysconfig.py", line 361, in _init_posix
ImportError: No module named _sysconfigdata

```

**Comment by niutech** [comment]
This is weird. My output on Windows is:
```
C:\>python.com
Current dir is
Env-var PATH is (null)
Cosmopolitan on Windows
sys.path in: lib/python27.zip:Lib:Lib/plat-linux2:build/lib.linux-x86_64-2.7
Python 2.7.18 (heads/cosmo_py27:d0cfff9f0e, Jun  9 2021, 08:22:33)
[GCC 9.3.0] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print("This line will be printed.")
This line will be printed.
```
and on Linux:
```
$ ./python.com
Current dir is /home/xxx/cpython
Env-var PATH is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/xxx/go/bin
sys.path in: lib/python27.zip:Lib:Lib/plat-linux2:build/lib.linux-x86_64-2.7
Python 2.7.18 (heads/cosmo_py27:d0cfff9f0e, Jun  9 2021, 08:22:33)
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print("This line will be printed.")
This line will be printed.
```
You are missing the 
[_sysconfigdata module](https://github.com/burggraf/awesome-cosmo/files/6627272/_sysconfigdata.zip). Extract it and add the files to `lib/python27.zip`.

**Comment by burggraf** [comment]
I’ve tested on MacOS and Ubuntu Linux 20.04.  Maybe it’s an environment variable that needs to be set?

**Comment by burggraf** [comment]
`You are missing the _sysconfigdata module. Extract the files and add them to lib/python27.zip.`

where are these files?

**Comment by burggraf** [comment]
Ah, I downloaded your files and added them to lib/python27.zip and it worked on MacOS.  I'll test Ubuntu and if that works I'll change the source download I made here.  Thanks!

**Comment by burggraf** [comment]
I updated the zip file in the lib folder -- all is good now.  Fixed!

**Comment by niutech** [comment]
Sorry, but there are more files missing inside subdirectories. I am uploading the updated 
[python27.zip](https://github.com/burggraf/awesome-cosmo/files/6627457/python27.zip).

**Comment by burggraf** [comment]
Updated the repo with your new lib.  Thanks.
