### ISSUE TITLE
Self-contained Python 2.7

### ISSUE THREAD

**Issue by niutech** [burggraf/awesome-cosmo#3]
I've built the latest version of APE Python 2.7 with its standard library bundled into a single `python.com` file. Here is the ZIP archive: 
[python.zip](https://github.com/burggraf/awesome-cosmo/files/6714872/python.zip). Please add it to the list.

**Comment by burggraf** [comment]
The version you sent did not have the libs, so I grabbed them from the last version and added them.  Please verify that this new zip file is correct and complete:  https://github.com/burggraf/awesome-cosmo/tree/main/apps/python2.7

**Comment by niutech** [comment]
The thing is that this version is self-contained, i.e. has the standard libs included in the single `python.com` file. No need for separate ZIP file. See [this commit](https://github.com/ahgamut/cpython/commit/51a29d96f9522baed63fc43bf3173081dcef7609).

**Comment by burggraf** [comment]
Got it.  All fixed.  Thank you!
